version: '3.8'
services: 
   back-end:
    container_name: back-end
    image: kbf-api
    restart: always
    build: 
       context: Api
       dockerfile : Dockerfile
    ports: 
          - 10.0.0.54:8080:8080
    environment:
        MYSQL_HOST: mysqldb
        MYSQL_USER: demosez
        MYSQL_PASSWORD: Aiyah@5108
        MYSQL_PORT: 3306
    depends_on:
      - mysqldb
   front-end:
       build:
         context: front-end
         dockerfile : Dockerfile
       ports: 
        - 10.0.0.54:80:80
       depends_on : 
        - back-end
   mysqldb:
    container_name: mysqldb
    image: mysql:8.0.32
    restart: always
    environment:
        MYSQL_DATABASE: kombe
        MYSQL_ROOT_PASSWORD: Aiyah@5108
        MYSQL_USER: demosez
        MYSQL_PASSWORD: Aiyah@5108       
    ports:
      - '10.0.0.54:3306:3306'
    volumes: 
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
      
   
 
    
#  db:
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       POSTGRES_USER : 'demosez'
#       POSTGRES_PASSWORD: 'Aiyah@5108'
#       POSTGRES_DB : kombe
#     ports:
#            - "50.215.60.97:5432:5432" 
#     volumes: 
#      - db:/var/lib/postgresql/data
#volumes:
#  db:
#    driver: local
#    environment:
#      MYSQL_HOST: mysqldb
#      MYSQL_USER: kombe
#      MYSQL_PASSWORD: Aiyah@5108
#      MYSQL_PORT: 3306
#  mysqldb: 
#    #container_name: mysqldb
#    image: mysql
#   # volumes:
#    #  -  /home/user/Desktop/db:/var/lib/mysql
#    ports: 
#     - 3307:3306   
#    environment:
#      MYSQL_DATABASE: kombe
#      MYSQL_ROOT_PASSWORD: Aiyah@5108
